config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'store', to: 'pages#store'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :articles
  resources :posts
  resources :quarks
  resources :leptons
  resources :protons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  validates :name, :presence => true
  validates :banner_image_url, :presence => true
  validates :title, :presence => true,
    :length => { :minimum => 5 }
  validates :content, :presence => true,
    :length => { :minimum => 5 }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  validates :name, :presence => true
  validates :banner_image_url, :presence => true
  validates :title, :presence => true,
    :length => { :minimum => 5 }
  validates :content, :presence => true,
    :length => { :minimum => 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:tag].present?
      @articles = Article.all.tagged_with(params[:tag])
    else
      @articles = Article.all.order("created_at DESC")
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
      flash[:success] =  "Article was successfully created."
    else
      render 'new'
      flash[:danger] = @article.errors.full_messages.join(", ")
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
      flash[:success] =  "Article was successfully updated."
    else
      render 'edit'
      flash[:danger] = @article.errors.full_messages.join(", ")
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:name, :title, :content, :tag_list, :banner_image_url)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end



  private
    def contact_params
       params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/leptons_controller.rb
class LeptonsController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 49900

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Lepton customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_lepton_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def store
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:tag].present?
      @posts = Post.all.tagged_with(params[:tag])
    else
      @posts = Post.all.order("created_at DESC")
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
      flash[:success] =  "Post was successfully created."
    else
      render 'new'
      flash[:danger] = @post.errors.full_messages.join(", ")
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
      flash[:success] =  "Post was successfully updated."
    else
      render 'edit'
      flash[:danger] = @post.errors.full_messages.join(", ")
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:name, :title, :content, :tag_list, :banner_image_url)
    end

end

app/controllers/protons_controller.rb
class ProtonsController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 99900

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Proton customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_proton_path
  end
end

app/controllers/quarks_controller.rb
class QuarksController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 24900

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Quark customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_quark_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/leptons_helper.rb
module LeptonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/protons_helper.rb
module ProtonsHelper
end

app/helpers/quarks_helper.rb
module QuarksHelper
end

app/views/articles/_form.html.erb
<%= form_for (article) do |f| %>

  <div class="row">
    <div class="col-md-3">
      <div class="field form-group">
        <%= f.text_field :name , class: 'contact-text-field-name', placeholder: "Name" %>
      </div>

      <div class="field form-group">
        <%= f.text_field :title , class: 'contact-text-field-name', placeholder: "Title" %>
      </div>

      <div class="field form-group">
        <%= f.text_field :banner_image_url , class: 'contact-text-field-name', placeholder: "Banner Image Url" %>
      </div>

      <div class="field form-group">
        <%= f.text_field :tag_list , class: 'contact-text-field-name', placeholder: "Tags" %>
      </div>
    </div>
    <div class="col-md-9">
      <div class="field form-group">
        <%= f.text_area :content , class: 'form-control tinymce' %>
      </div>
    </div>
  </div>

  <div class="actions form-group">
    <%= f.submit "Save Article", :class => 'invert-button'%>
    <%= link_to 'Back', articles_path , :class => 'invert-button'%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Article</h1>
  <%= render 'form', article: @article %>
</div>

app/views/articles/index.html.erb
<div class="w3-content" style="max-width:1400px">
  <!-- Grid -->
  <div class="w3-row">

  <!-- Blog entries -->
  <div class="w3-col l8 s12">
    <!-- Blog entry -->
    <% @articles.each do |article| %>
    <div class="w3-card-4 w3-margin w3-white">
      <img src="<%= article.banner_image_url %>" alt="" style="width:100%" >
      <div class="w3-container w3-padding-8">
        <h1 id=""><b><%= article.title %></b></h1>
        <h5 id=""><%= article.name %> , <span class="w3-opacity"><%= time_ago_in_words(article.created_at) %> ago</span></h5>
      </div>

      <div class="w3-container">
        <p id=""><%=raw article.content.truncate(323) %></p>
        <div class="w3-row">
          <div class="w3-col m8 s12">
            <%= button_to "READ MORE", article, class: 'invert-button', :method => "get" %>
          </div>
          <div class="w3-col m4 w3-hide-small">
            <p class="w3-right" href="#disqus_thread"><b>Comments </b> <span class="w3-tag"><script id="dsq-count-scr" src="//apexverse.disqus.com/count.js" async></script></span></p>
          </div>
        </div>
      </div>
      <br>
    </div>
    <% end %>
  <!-- END BLOG ENTRIES -->
  </div>

  <!-- Introduction menu -->
  <div class="w3-col l4">

    <!-- Most Popular Posts -->
    <div class="w3-card-2 w3-margin">
      <div class="w3-container w3-padding">
        <h4>Popular Articles</h4>
      </div>
      <ul class="w3-ul w3-hoverable w3-white">
        <% @articles.first(5).shuffle.each do |article| %>
        <li class="w3-padding-16">
          <span class="w3-large"><%= link_to article.title, article%></span><br>
          <span><%= article.created_at.strftime("%B %d %Y") %></span>
        </li>
        <% end %>
      </ul>
    </div>


    <!-- Labels / tags -->
    <div class="w3-card-2 w3-margin">
      <div class="w3-container w3-padding">
        <h4>Tags</h4>
      </div>
      <div class="w3-container w3-white">
        <p>
          <% ActsAsTaggableOn::Tag.all.each do |tag| %>
            <span class="w3-tag w3-light-grey w3-small w3-margin-bottom"><%= link_to tag.name, articles_path(tag: tag.name) %></span>
          <% end %>
        </p>
      </div>
    </div>
  <!-- END Introduction Menu -->
  </div>
  <!-- END GRID -->
  </div><br>

</div>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="text-center">New Article</h1>
  <%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<div class="container" id= "article-container">
  <meta name="description" content="<%= h truncate(@article.content, :length => 255) %>">
  <div class="intro-header">
      <div class="container">
        <div class="article-heading">
          <h1 id="article-title"><%= @article.title %></h1>
          <div class="w3-row">
            <p id="article-name">By <%= @article.name %> on <%= @article.created_at.strftime("%B %d, %Y") %></p>
            <% @article.tags.each do |tag| %>
              <span class="w3-tag w3-light-grey w3-small w3-margin-bottom"><%= link_to tag.name, articles_path(tag: tag.name) %></span>
            <% end %>
          </div>
        </div>
      </div>
  </div>
  <br>
  <article>
    <div class="container" id="article-content-container">
      <p id="article-content"><%= @article.content.html_safe %></p>
    </div>
  </article>
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_article_path(@article), :class => 'btn btn-warning' %>
      <%= link_to 'Delete', article_path(@article), method: :delete, :class => 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div><br><br>

  <div class="container">
    <div id="disqus_thread"></div>
    <script>

    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://apexverse.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  </div>

</div>

app/views/contacts/new.html.erb
<div class="container">
    <h1 class="text-center">Contact Us</h1>
    <div class="">
      <%= form_for @contact do |f| %>
        <div class="w3-row">
          <div class="w3-col" style="width: 50%">
          <%= f.text_field :name, class: 'contact-text-field-name', placeholder: "Name" %>
          </div>
          <div class="w3-col" style="width: 50%">
          <%= f.text_field :email, class: 'contact-text-field-email', placeholder: "Email" %>
          </div>

        </div>
        <div class="form-group">
          <%= f.text_area :comments, class: 'contact-text-area', placeholder: "Message" %>
        </div>
        <%= f.submit 'Submit', class: 'invert-button' %>
      <% end %>
    </div>
    <br>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= if content_for?(:title) then yield(:title) + ' | ' end %>
      ApexVerse
    </title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//fonts.googleapis.com/css?family=Cinzel|Dancing+Script|Open+Sans|Questrial|Russo+One|Lato|Montserrat|Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Nav Bar-->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <div class="row">
              ApexVerse
            </div>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= 'active' if current_page?(articles_path) %>"><%= link_to "News", articles_path %></li>
            <li class="<%= 'active' if current_page?(posts_path) %>"><%= link_to "Media", posts_path %></li>
            <li class="<%= 'active' if current_page?(store_path) %>"><%= link_to "Store", store_path %></li>
            <li class="<%= 'active' if current_page?(new_contact_path) %>"><%= link_to "Contact Us", new_contact_path %></li>
            <% if user_signed_in? %><li class="<%= 'active' if current_page?(new_article_path) %>"><%= link_to 'New Article', new_article_path %></li><% end %>
            <% if user_signed_in? %><li class="<%= 'active' if current_page?(new_post_path) %>"><%= link_to 'New Post', new_post_path %></li><% end %>
            <% if user_signed_in? %><li class="<%= 'active' if current_page?(destroy_user_session_path) %>"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li><% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>


    <!--Dynamic Flash Message-->
    <div class="container"><%= render 'layouts/messages' %></div>

    <!--Main Content-->
    <%= yield %>

    <!-- Footer -->
    <footer class="w3-container w3-padding-32 w3-light-grey w3-center">
      <a href="#" class="w3-btn w3-black w3-hover-white"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
      <div class="w3-xlarge w3-section">
        <a href="https://www.facebook.com/ApexVerse" class="fa fa-facebook-official w3-hover-text-indigo" style="text-decoration:none"></a>
        <a href="https://twitter.com/ApexVerse" class="fa fa-twitter w3-hover-text-light-blue" style="text-decoration:none"></a>
        <a href="https://www.instagram.com/ApexVerse/" class="fa fa-instagram w3-hover-text-purple" style="text-decoration:none"></a>
      </div>
      <p>Copyright <%= link_to "\u00A9", new_user_session_path, class: "w3-hover-text-green"%> ApexVerse 2017</p>
    </footer>

  </body>
</html>

app/views/leptons/create.html.erb
<div class="w3-container w3-padding-32 w3-center">
  <h2>Thanks, you paid <strong>$499.00</strong>!</h2>
  <h2>Please contact us for any special requests or specifications you may have
  and we'll get back to you shortly.</h2>
  <h2>Thank you!</h2>
</div>

app/views/leptons/new.html.erb
<%= form_tag leptons_path do %>
  <div class="w3-container w3-padding-32 w3-center" id="website-pricing">
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>
    <div class="container" style="max-width:1400px">
      <div class="w3-row-padding">
        <div class="w3-section" id="website-lepton">
          <ul class="w3-ul w3-white w3-hover-shadow">
            <li class="w3-black w3-xlarge w3-padding-32">Lepton</li>
            <li class="w3-padding-16"><b>6-8 Page Custom Website</b></li>
            <li class="w3-padding-16">Mobile Responsive</li>
            <li class="w3-padding-16">Google Analytic Integration</li>
            <li class="w3-padding-16">Hosting Set-up</li>
            <li class="w3-padding-16">Domain name</li>
            <li class="w3-padding-16">100% Satisfaction Guaranteed</li>
            <li class="w3-padding-16"><b>Free</b> 6 Months Maintenance</li>
            <li class="w3-padding-16">
              <h2><strike>$999</strike><b> $499</b></h2>
            </li>
            <li class="w3-light-grey w3-padding-32">
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="The Lepton Package"
                      data-amount="49900"
                      data-locale="auto"></script>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for (post) do |f| %>

  <div class="row">
    <div class="col-md-3">
      <div class="field form-group">
        <%= f.text_field :name , class: 'contact-text-field-name', placeholder: "Name" %>
      </div>

      <div class="field form-group">
        <%= f.text_field :title , class: 'contact-text-field-name', placeholder: "Title" %>
      </div>

      <div class="field form-group">
        <%= f.text_field :banner_image_url , class: 'contact-text-field-name', placeholder: "Banner Image Url" %>
      </div>

      <div class="field form-group">
        <%= f.text_field :tag_list , class: 'contact-text-field-name', placeholder: "Tags" %>
      </div>
    </div>
    <div class="col-md-9">
      <div class="field form-group">
        <%= f.text_area :content , class: 'form-control tinymce' %>
      </div>
    </div>
  </div>

  <div class="actions form-group">
    <%= f.submit "Save Post", :class => 'invert-button'%>
    <%= link_to 'Back', posts_path , :class => 'invert-button'%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Post</h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="text-center">New Post</h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="container" id= "post-container">
  <meta name="description" content="<%= h truncate(@post.content, :length => 255) %>">
  <div class="intro-header">
      <div class="container">
        <div class="post-heading">
          <h1 id="post-title"><%= @post.title %></h1>
          <div class="w3-row">
            <p id="post-name">By <%= @post.name %> on <%= @post.created_at.strftime("%B %d, %Y") %></p>
            <% @post.tags.each do |tag| %>
              <span class="w3-tag w3-light-grey w3-small w3-margin-bottom"><%= link_to tag.name, posts_path(tag: tag.name) %></span>
            <% end %>
          </div>
        </div>
      </div>
  </div>
  <br>
  <post>
    <div class="container" id="post-content-container">
      <p id="post-content"><%= @post.content.html_safe %></p>
    </div>
  </post>
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-warning' %>
      <%= link_to 'Delete', post_path(@post), method: :delete, :class => 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div><br><br>
  
  <div class="container">
    <div id="disqus_thread"></div>
    <script>

    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://apexverse.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  </div>

</div>

app/views/protons/create.html.erb
<div class="w3-container w3-padding-32 w3-center">
  <h2>Thanks, you paid <strong>$999.00</strong>!</h2>
  <h2>Please contact us for any special requests or specifications you may have
  and we'll get back to you shortly.</h2>
  <h2>Thank you!</h2>
</div>

app/views/protons/new.html.erb
<%= form_tag protons_path do %>
  <div class="w3-container w3-padding-32 w3-center" id="website-pricing">
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>
    <div class="container" style="max-width:1400px">
      <div class="w3-row-padding">
        <div class="w3-section" id="website-proton">
          <ul class="w3-ul w3-white w3-hover-shadow">
            <li class="w3-black w3-xlarge w3-padding-32">Proton</li>
            <li class="w3-padding-16">10 Page Custom Website</li>
            <li class="w3-padding-16">Mobile Responsive</li>
            <li class="w3-padding-16">Google Analytic Integration</li>
            <li class="w3-padding-16">Ad Revenue Consulting</li>
            <li class="w3-padding-16">Hosting Set-up</li>
            <li class="w3-padding-16">Domain name</li>
            <li class="w3-padding-16">100% Satisfaction Guaranteed</li>
            <li class="w3-padding-16"><b>Free</b> 1 year Maintenance</li>
            <li class="w3-padding-16">
              <h2 ><strike>$1499</strike><b> $999 </b></h2>
            </li>
            <li class="w3-light-grey w3-padding-32">
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="The Proton Package"
                      data-amount="99900"
                      data-locale="auto"></script>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/quarks/create.html.erb
<div class="w3-container w3-padding-32 w3-center">
  <h2>Thanks, you paid <strong>$249.00</strong>!</h2>
  <h2>Please contact us for any special requests or specifications you may have
  and we'll get back to you shortly.</h2>
  <h2>Thank you!</h2>
</div>

app/views/quarks/new.html.erb
<%= form_tag quarks_path do %>
  <div class="w3-container w3-padding-32 w3-center" id="website-pricing">
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>
    <div class="container" style="max-width:1400px">
      <div class="w3-row-padding">
        <div class="w3-section" id="website-quark">
          <ul class="w3-ul w3-white w3-hover-shadow">
            <li class="w3-black w3-xlarge w3-padding-32">Quark</li>
            <li class="w3-padding-16"><b>3-5 Page Custom Website</b></li>
            <li class="w3-padding-16">Mobile Responsive</li>
            <li class="w3-padding-16">Hosting Set-up</li>
            <li class="w3-padding-16">Domain name</li>
            <li class="w3-padding-16">100% Satisfaction Guaranteed</li>
            <li class="w3-padding-16"><b>Free</b> 6 Months Maintenance</li>
            <li class="w3-padding-16">
              <h2><strike>$599</strike><b> $249</b></h2>
            </li>
            <li class="w3-light-grey w3-padding-32">
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="The Quark Package"
                      data-amount="24900"
                      data-locale="auto"></script>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>